# Generated by Django 4.1.3 on 2022-11-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=500, verbose_name='Summary')),
                ('detail', models.TextField(verbose_name='Detail')),
                ('deadline', models.DateTimeField(blank=True)),
            ],
        ),
    ]
